### ISSUE TITLE
getting Angular error on toggleSwitch

### ISSUE THREAD

**Issue by eturino** [opentable/hobknob#127]
I thought it could be a problem with HTTPS, but I'm getting this now even in my local, even with previous master.

getting Angular error that prevents the switch to work. Kind of a needed feature on hobknob :)

I don't know how could be possible that this is failing now even after reverting everything, even in my local. Am I doing something wrong?

```
Error: [$compile:ctreq] http://errors.angularjs.org/1.2.28/$compile/ctreq?p0=ngModel&p1=toggleSwitch
    at Error (native)
    at http://localhost:3006/bower_components/angular/angular.min.js:6:450
    at t (http://localhost:3006/bower_components/angular/angular.min.js:51:369)
    at J (http://localhost:3006/bower_components/angular/angular.min.js:54:409)
    at g (http://localhost:3006/bower_components/angular/angular.min.js:47:256)
    at g (http://localhost:3006/bower_components/angular/angular.min.js:47:273)
    at g (http://localhost:3006/bower_components/angular/angular.min.js:47:273)
    at J (http://localhost:3006/bower_components/angular/angular.min.js:54:314)
    at g (http://localhost:3006/bower_components/angular/angular.min.js:47:256)
    at http://localhost:3006/bower_components/angular/angular.min.js:46:377 <div class="switch-primary ats-switch ng-isolate-scope" ng-click="toggle()" ng-class="{ 'disabled': isDisabled }" model="toggle.value" on-change="updateThisToggle(toggle)" ng-disabled="userHasPermissionsLoaded &amp;&amp; !userHasPermissions" data-toggle="{{toggle.name}}">(anonymous function) @ angular.min.js:92
```

https://docs.angularjs.org/error/$compile/ctreq?p0=ngModel&p1=toggleSwitch

**Comment by stevejhiggs** [comment]
There's something eerily familiar about this. I'll try to take a look at it

**Comment by eturino** [comment]
I changed all the dependencies in bower.json to use specific versions instead of fuzzy ones (~), and works. Looks like one of the latest minor versions is breaking up things nicely. I'll try to narrow it down.

**Comment by stevejhiggs** [comment]
ah, thats how it was familiar. Thanks!

**Comment by andyroyle** [comment]
yeah, I just managed to reproduce by clearing the bower packages and reinstalling

**Comment by eturino** [comment]
narrowed it down to 
```
"angular-bootstrap-toggle-switch": "0.5.1",
```

**Comment by andyroyle** [comment]
I found that too. Latest version is `0.5.4` which doesn't work, whereas `0.5.1` does

**Comment by andyroyle** [comment]
fixing `angular-bootstrap-toggle-switch` to `0.5.1` (and leaving all the others fuzzy) seems to fix it

**Comment by eturino** [comment]
actually `0.5.2` works too. `0.5.3` and `0.5.4` break.

**Comment by eturino** [comment]
I'll create a PR fixing it to `0.5.2`, but could you contact them to see what's wrong? I'm not an angular dev and my ability to help would be quite limited :)

**Comment by eturino** [comment]
https://github.com/opentable/hobknob/pull/128

**Comment by andyroyle** [comment]
I had a look through the changelog between 0.5.2 and 0.5.3 and couldn't see anything obvious. The only significant change is this:https://github.com/JumpLink/angular-toggle-switch/commit/3792109138cd84aa46d8f4490d2ceb4985c76b91
